site_name: Dataflow Agent Docs
site_url: ""
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - content.code.annotate
nav:
  - 主页: index.md
  - 教程:
      - workflow编写指南: tutorials/workflow_write.md
  - 指南:
      - 架构设计: guides/architecture.md
  - FAQ: faq.md
  - 贡献指南: contributing.md
  - 更新日志: changelog.md
markdown_extensions:
  - admonition
  - toc:
      permalink: ⚓︎
  - pymdownx.superfences
  - pymdownx.highlight
plugins:
  - search
